/*
 * generated by Xtext 2.25.0
 */
package game.of.life.ui.tests;

import com.google.inject.Injector;
import game.of.life.ui.internal.LifeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LifeDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LifeActivator.getInstance().getInjector("game.of.life.LifeDsl");
	}

}
