/*
 * generated by Xtext 2.25.0
 */
package game.of.life.ui;

import com.google.inject.Injector;
import game.of.life.ui.internal.LifeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LifeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LifeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LifeActivator activator = LifeActivator.getInstance();
		return activator != null ? activator.getInjector(LifeActivator.GAME_OF_LIFE_LIFEDSL) : null;
	}

}
