/*
 * generated by Xtext 2.25.0
 */
package game.of.life.parser.antlr;

import com.google.inject.Inject;
import game.of.life.parser.antlr.internal.InternalLifeDslParser;
import game.of.life.services.LifeDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LifeDslParser extends AbstractAntlrParser {

	@Inject
	private LifeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLifeDslParser createParser(XtextTokenStream stream) {
		return new InternalLifeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public LifeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LifeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
