/*
 * generated by Xtext 2.25.0
 */
package game.of.life.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LifeDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("game/of/life/parser/antlr/internal/InternalLifeDsl.tokens");
	}
}
