/*
 * generated by Xtext 2.25.0
 */
package game.of.life.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLifeDslScopeProvider extends DelegatingScopeProvider {
}
