/*
 * generated by Xtext 2.25.0
 */
package game.of.life.validation

import game.of.life.lifeDsl.Model
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class LifeDslValidator extends AbstractLifeDslValidator {
	
@Check
    def checkDoubleInitialGrids(Model root) {
        var glist = root.grids // lists start at position 0
        for (var i = 0; i < glist.size; i++) {
            for (var j = i + 1; j < glist.size; j++) {
                if (
                	glist.get(i).row.equals(glist.get(j).row) 
                	&& glist.get(i).column.equals(glist.get(j).column)
                ) {
                    error("Double grid", null)
                }
            }
        }
    }
	
}
