/**
 * generated by Xtext 2.25.0
 */
package game.of.life.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import game.of.life.LifeDslRuntimeModule;
import game.of.life.LifeDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LifeDslIdeSetup extends LifeDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    LifeDslRuntimeModule _lifeDslRuntimeModule = new LifeDslRuntimeModule();
    LifeDslIdeModule _lifeDslIdeModule = new LifeDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_lifeDslRuntimeModule, _lifeDslIdeModule));
  }
}
