/**
 * generated by Xtext 2.25.0
 */
package game.of.life.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LifeDslIdeModule extends AbstractLifeDslIdeModule {
}
