/**
 * generated by Xtext 2.25.0
 */
package game.of.life.lifeDsl.impl;

import game.of.life.lifeDsl.DieAliveUnit;
import game.of.life.lifeDsl.EvolutionRules;
import game.of.life.lifeDsl.LifeDslPackage;
import game.of.life.lifeDsl.OperatorUnit;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evolution Rules</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.lifeDsl.impl.EvolutionRulesImpl#getName <em>Name</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.impl.EvolutionRulesImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.impl.EvolutionRulesImpl#getNumberOfLiveNeighbors <em>Number Of Live Neighbors</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EvolutionRulesImpl extends MinimalEObjectImpl.Container implements EvolutionRules
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final DieAliveUnit NAME_EDEFAULT = DieAliveUnit.DIE;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected DieAliveUnit name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected static final OperatorUnit OPERATOR_EDEFAULT = OperatorUnit.EQ;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected OperatorUnit operator = OPERATOR_EDEFAULT;

  /**
   * The default value of the '{@link #getNumberOfLiveNeighbors() <em>Number Of Live Neighbors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfLiveNeighbors()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_OF_LIVE_NEIGHBORS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumberOfLiveNeighbors() <em>Number Of Live Neighbors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfLiveNeighbors()
   * @generated
   * @ordered
   */
  protected int numberOfLiveNeighbors = NUMBER_OF_LIVE_NEIGHBORS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvolutionRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LifeDslPackage.Literals.EVOLUTION_RULES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DieAliveUnit getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(DieAliveUnit newName)
  {
    DieAliveUnit oldName = name;
    name = newName == null ? NAME_EDEFAULT : newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LifeDslPackage.EVOLUTION_RULES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperatorUnit getOperator()
  {
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperator(OperatorUnit newOperator)
  {
    OperatorUnit oldOperator = operator;
    operator = newOperator == null ? OPERATOR_EDEFAULT : newOperator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LifeDslPackage.EVOLUTION_RULES__OPERATOR, oldOperator, operator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumberOfLiveNeighbors()
  {
    return numberOfLiveNeighbors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumberOfLiveNeighbors(int newNumberOfLiveNeighbors)
  {
    int oldNumberOfLiveNeighbors = numberOfLiveNeighbors;
    numberOfLiveNeighbors = newNumberOfLiveNeighbors;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LifeDslPackage.EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS, oldNumberOfLiveNeighbors, numberOfLiveNeighbors));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LifeDslPackage.EVOLUTION_RULES__NAME:
        return getName();
      case LifeDslPackage.EVOLUTION_RULES__OPERATOR:
        return getOperator();
      case LifeDslPackage.EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS:
        return getNumberOfLiveNeighbors();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LifeDslPackage.EVOLUTION_RULES__NAME:
        setName((DieAliveUnit)newValue);
        return;
      case LifeDslPackage.EVOLUTION_RULES__OPERATOR:
        setOperator((OperatorUnit)newValue);
        return;
      case LifeDslPackage.EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS:
        setNumberOfLiveNeighbors((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LifeDslPackage.EVOLUTION_RULES__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LifeDslPackage.EVOLUTION_RULES__OPERATOR:
        setOperator(OPERATOR_EDEFAULT);
        return;
      case LifeDslPackage.EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS:
        setNumberOfLiveNeighbors(NUMBER_OF_LIVE_NEIGHBORS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LifeDslPackage.EVOLUTION_RULES__NAME:
        return name != NAME_EDEFAULT;
      case LifeDslPackage.EVOLUTION_RULES__OPERATOR:
        return operator != OPERATOR_EDEFAULT;
      case LifeDslPackage.EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS:
        return numberOfLiveNeighbors != NUMBER_OF_LIVE_NEIGHBORS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", operator: ");
    result.append(operator);
    result.append(", numberOfLiveNeighbors: ");
    result.append(numberOfLiveNeighbors);
    result.append(')');
    return result.toString();
  }

} //EvolutionRulesImpl
