/**
 * generated by Xtext 2.25.0
 */
package game.of.life.lifeDsl.impl;

import game.of.life.lifeDsl.DieAliveUnit;
import game.of.life.lifeDsl.EvolutionRules;
import game.of.life.lifeDsl.InitialGrid;
import game.of.life.lifeDsl.LifeDslFactory;
import game.of.life.lifeDsl.LifeDslPackage;
import game.of.life.lifeDsl.Model;
import game.of.life.lifeDsl.Operator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LifeDslPackageImpl extends EPackageImpl implements LifeDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialGridEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass evolutionRulesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum operatorEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum dieAliveUnitEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see game.of.life.lifeDsl.LifeDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private LifeDslPackageImpl()
  {
    super(eNS_URI, LifeDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link LifeDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static LifeDslPackage init()
  {
    if (isInited) return (LifeDslPackage)EPackage.Registry.INSTANCE.getEPackage(LifeDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredLifeDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    LifeDslPackageImpl theLifeDslPackage = registeredLifeDslPackage instanceof LifeDslPackageImpl ? (LifeDslPackageImpl)registeredLifeDslPackage : new LifeDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theLifeDslPackage.createPackageContents();

    // Initialize created meta-data
    theLifeDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theLifeDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(LifeDslPackage.eNS_URI, theLifeDslPackage);
    return theLifeDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Grid()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Rules()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialGrid()
  {
    return initialGridEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialGrid_CellsX()
  {
    return (EAttribute)initialGridEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialGrid_CellsY()
  {
    return (EAttribute)initialGridEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEvolutionRules()
  {
    return evolutionRulesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEvolutionRules_Name()
  {
    return (EAttribute)evolutionRulesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEvolutionRules_Operator()
  {
    return (EAttribute)evolutionRulesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEvolutionRules_NumberOfLiveNeighbors()
  {
    return (EAttribute)evolutionRulesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getOperator()
  {
    return operatorEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDieAliveUnit()
  {
    return dieAliveUnitEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LifeDslFactory getLifeDslFactory()
  {
    return (LifeDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__GRID);
    createEReference(modelEClass, MODEL__RULES);

    initialGridEClass = createEClass(INITIAL_GRID);
    createEAttribute(initialGridEClass, INITIAL_GRID__CELLS_X);
    createEAttribute(initialGridEClass, INITIAL_GRID__CELLS_Y);

    evolutionRulesEClass = createEClass(EVOLUTION_RULES);
    createEAttribute(evolutionRulesEClass, EVOLUTION_RULES__NAME);
    createEAttribute(evolutionRulesEClass, EVOLUTION_RULES__OPERATOR);
    createEAttribute(evolutionRulesEClass, EVOLUTION_RULES__NUMBER_OF_LIVE_NEIGHBORS);

    // Create enums
    operatorEEnum = createEEnum(OPERATOR);
    dieAliveUnitEEnum = createEEnum(DIE_ALIVE_UNIT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Grid(), this.getInitialGrid(), null, "grid", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Rules(), this.getEvolutionRules(), null, "rules", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialGridEClass, InitialGrid.class, "InitialGrid", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialGrid_CellsX(), ecorePackage.getEString(), "cellsX", null, 0, 1, InitialGrid.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getInitialGrid_CellsY(), ecorePackage.getEString(), "cellsY", null, 0, 1, InitialGrid.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(evolutionRulesEClass, EvolutionRules.class, "EvolutionRules", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEvolutionRules_Name(), this.getDieAliveUnit(), "name", null, 0, 1, EvolutionRules.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEvolutionRules_Operator(), this.getOperator(), "operator", null, 0, 1, EvolutionRules.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEvolutionRules_NumberOfLiveNeighbors(), ecorePackage.getEInt(), "numberOfLiveNeighbors", null, 0, 1, EvolutionRules.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(operatorEEnum, Operator.class, "Operator");
    addEEnumLiteral(operatorEEnum, Operator.LT);
    addEEnumLiteral(operatorEEnum, Operator.EQ);
    addEEnumLiteral(operatorEEnum, Operator.GT);

    initEEnum(dieAliveUnitEEnum, DieAliveUnit.class, "DieAliveUnit");
    addEEnumLiteral(dieAliveUnitEEnum, DieAliveUnit.DIE);
    addEEnumLiteral(dieAliveUnitEEnum, DieAliveUnit.LIVE);
    addEEnumLiteral(dieAliveUnitEEnum, DieAliveUnit.BECOME_ALIVE);

    // Create resource
    createResource(eNS_URI);
  }

} //LifeDslPackageImpl
