/**
 * generated by Xtext 2.25.0
 */
package game.of.life.lifeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evolution Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.lifeDsl.EvolutionRules#getName <em>Name</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.EvolutionRules#getOperator <em>Operator</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.EvolutionRules#getNumberOfLiveNeighbors <em>Number Of Live Neighbors</em>}</li>
 * </ul>
 *
 * @see game.of.life.lifeDsl.LifeDslPackage#getEvolutionRules()
 * @model
 * @generated
 */
public interface EvolutionRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link game.of.life.lifeDsl.DieAliveUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see game.of.life.lifeDsl.DieAliveUnit
   * @see #setName(DieAliveUnit)
   * @see game.of.life.lifeDsl.LifeDslPackage#getEvolutionRules_Name()
   * @model
   * @generated
   */
  DieAliveUnit getName();

  /**
   * Sets the value of the '{@link game.of.life.lifeDsl.EvolutionRules#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see game.of.life.lifeDsl.DieAliveUnit
   * @see #getName()
   * @generated
   */
  void setName(DieAliveUnit value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link game.of.life.lifeDsl.OperatorUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see game.of.life.lifeDsl.OperatorUnit
   * @see #setOperator(OperatorUnit)
   * @see game.of.life.lifeDsl.LifeDslPackage#getEvolutionRules_Operator()
   * @model
   * @generated
   */
  OperatorUnit getOperator();

  /**
   * Sets the value of the '{@link game.of.life.lifeDsl.EvolutionRules#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see game.of.life.lifeDsl.OperatorUnit
   * @see #getOperator()
   * @generated
   */
  void setOperator(OperatorUnit value);

  /**
   * Returns the value of the '<em><b>Number Of Live Neighbors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Of Live Neighbors</em>' attribute.
   * @see #setNumberOfLiveNeighbors(int)
   * @see game.of.life.lifeDsl.LifeDslPackage#getEvolutionRules_NumberOfLiveNeighbors()
   * @model
   * @generated
   */
  int getNumberOfLiveNeighbors();

  /**
   * Sets the value of the '{@link game.of.life.lifeDsl.EvolutionRules#getNumberOfLiveNeighbors <em>Number Of Live Neighbors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number Of Live Neighbors</em>' attribute.
   * @see #getNumberOfLiveNeighbors()
   * @generated
   */
  void setNumberOfLiveNeighbors(int value);

} // EvolutionRules
