/**
 * generated by Xtext 2.25.0
 */
package game.of.life.lifeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.lifeDsl.Grid#getRow <em>Row</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.Grid#getColumn <em>Column</em>}</li>
 * </ul>
 *
 * @see game.of.life.lifeDsl.LifeDslPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' attribute.
   * @see #setRow(int)
   * @see game.of.life.lifeDsl.LifeDslPackage#getGrid_Row()
   * @model
   * @generated
   */
  int getRow();

  /**
   * Sets the value of the '{@link game.of.life.lifeDsl.Grid#getRow <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' attribute.
   * @see #getRow()
   * @generated
   */
  void setRow(int value);

  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(int)
   * @see game.of.life.lifeDsl.LifeDslPackage#getGrid_Column()
   * @model
   * @generated
   */
  int getColumn();

  /**
   * Sets the value of the '{@link game.of.life.lifeDsl.Grid#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(int value);

} // Grid
