/**
 * generated by Xtext 2.25.0
 */
package game.of.life.lifeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.lifeDsl.Model#getGrids <em>Grids</em>}</li>
 *   <li>{@link game.of.life.lifeDsl.Model#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see game.of.life.lifeDsl.LifeDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Grids</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.lifeDsl.Grid}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grids</em>' containment reference list.
   * @see game.of.life.lifeDsl.LifeDslPackage#getModel_Grids()
   * @model containment="true"
   * @generated
   */
  EList<Grid> getGrids();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.lifeDsl.EvolutionRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see game.of.life.lifeDsl.LifeDslPackage#getModel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<EvolutionRules> getRules();

} // Model
